---
title: "Daily THD visualisation with Filter on off"
output: html_notebook
---
```{r}
# Importing libraries and reading data
library(ggplot2)
library(gridExtra)
library(reshape)
library(lubridate)
library(zoo)
library(plyr)
library(tidyr)
library(hexbin)
m46 <- read.csv("data/combined/46combined1.csv")
m60 <- read.csv("data/combined/60combined1.csv")
```
```{r}
# Transforming date and time variables
m46$StartTime <- as.POSIXct(m46$StartTime, format = "%Y-%m-%d %H:%M:%S")
m60$StartTime <- as.POSIXct(m60$StartTime, format = "%Y-%m-%d %H:%M:%S")
m46$B11time <- as.POSIXct(m46$B11time, format = "%Y-%m-%d %H:%M:%S")
m60$B11time <- as.POSIXct(m60$B11time, format = "%Y-%m-%d %H:%M:%S")
m46$B12time <- as.POSIXct(m46$B12time, format = "%Y-%m-%d %H:%M:%S")
m60$B12time <- as.POSIXct(m60$B12time, format = "%Y-%m-%d %H:%M:%S")
m46$B21time <- as.POSIXct(m46$B21time, format = "%Y-%m-%d %H:%M:%S")
m60$B21time <- as.POSIXct(m60$B21time, format = "%Y-%m-%d %H:%M:%S")
m46$B22time <- as.POSIXct(m46$B22time, format = "%Y-%m-%d %H:%M:%S")
m60$B22time <- as.POSIXct(m60$B22time, format = "%Y-%m-%d %H:%M:%S")

# Combining the dataset
m46$type <- "m46"
m60$type <- "m60"

# Adding time specific columns
m46$month <- month.abb[month(m46$StartTime)]
m46$time  <- time(m46$StartTime)
m46$day   <- day(m46$StartTime)

m60$month <- month.abb[month(m60$StartTime)]
m60$time  <- time(m60$StartTime)
m60$day   <- day(m60$StartTime)

# Partitioning data by month
m46$monthorder <- 0
m46[m46$month == 'Nov', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Nov',]), 1)
m46[m46$month == 'Dec', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Dec',]), 1)
m46[m46$month == 'Jan', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Jan',]), 1)
m46[m46$month == 'Feb', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Feb',]), 1)
m46[m46$month == 'Mar', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Mar',]), 1)
m46[m46$month == 'Apr', c('monthorder')] <- seq(1, nrow(m46[m46$month == 'Apr',]), 1)
m46$month <- factor(m46$month, c("Nov", "Dec", "Jan", "Feb", "Mar", "Apr")) #Ordering based on months

m60$monthorder <- 0
m60[m60$month == 'Nov', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Nov',]), 1)
m60[m60$month == 'Dec', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Dec',]), 1)
m60[m60$month == 'Jan', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Jan',]), 1)
m60[m60$month == 'Feb', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Feb',]), 1)
m60[m60$month == 'Mar', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Mar',]), 1)
m60[m60$month == 'Apr', c('monthorder')] <- seq(1, nrow(m60[m60$month == 'Apr',]), 1)
m60$month <- factor(m60$month, c("Nov", "Dec", "Jan", "Feb", "Mar", "Apr")) #Ordering based on months

# Partitioning data by day of the week
m46$wday <- wday(m46$StartTime, label=TRUE)
m46$dayorder <- 0
months = c('Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr')
days = 1:31
for (month in months){
  for (day in days){
    if (max(m46[m46$month==month,'day']) < day){
      next
    }
    m46[m46$month == month & m46$day == day, c('dayorder')] <- 1:nrow(m46[m46$month == month & m46$day == day, ])
  }
}

m60$wday <- wday(m60$StartTime, label=TRUE)
m60$dayorder <- 0
months = c('Nov', 'Dec', 'Jan', 'Feb', 'Mar', 'Apr')
days = 1:31
for (month in months){
  for (day in days){
    if (max(m60[m60$month==month,'day']) < day){
      next
    }
    m60[m60$month == month & m60$day == day, c('dayorder')] <- 1:nrow(m60[m60$month == month & m60$day == day, ])
  }
}

# Adding week number data
m46$week <- week(m46$StartTime)
m60$week <- week(m60$StartTime)

# combining datasets
df <- rbind(m46, m60)
```

```{r}
df$readdate <- paste(df$month, df$day)
order <- unique(df$readdate)
df$readdate <- factor(df$readdate, order)
```

```{r}
df$B11dif <- as.numeric(difftime(df$StartTime, df$B11time, units = 'secs'))
df$B12dif <- as.numeric(difftime(df$StartTime, df$B12time, units = 'secs'))
df$B21dif <- as.numeric(difftime(df$StartTime, df$B21time, units = 'secs'))
df$B22dif <- as.numeric(difftime(df$StartTime, df$B22time, units = 'secs'))

df$B11month <- month.abb[month(df$B11time)]
df$B12month <- month.abb[month(df$B12time)]
df$B21month <- month.abb[month(df$B21time)]
df$B22month <- month.abb[month(df$B22time)]

df$B11dif=df$B11dif/3600
df$B12dif=df$B12dif/3600
df$B21dif=df$B21dif/3600
df$B22dif=df$B22dif/3600
```


```{r}
ggplot(data=df[df$type=='m46',],aes(x=B11dif,y=B11THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B11) + xlab('Time Elapsed (in hours)') + ggtitle('B11') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m46',],aes(x=B12dif,y=B12THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B12) + xlab('Time Elapsed (in hours)') + ggtitle('B12') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m46',],aes(x=B21dif,y=B21THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B21) + xlab('Time Elapsed (in hours)') + ggtitle('B21') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m46',],aes(x=B22dif,y=B22THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B22) + xlab('Time Elapsed (in hours)') + ggtitle('B22') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
```

```{r}
ggplot(data=df[df$type=='m60',],aes(x=B11dif,y=B11THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B11) + xlab('Time Elapsed (in hours)') + ggtitle('B11') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m60',],aes(x=B12dif,y=B12THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B12) + xlab('Time Elapsed (in hours)') + ggtitle('B12') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m60',],aes(x=B21dif,y=B21THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B21) + xlab('Time Elapsed (in hours)') + ggtitle('B21') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
ggplot(data=df[df$type=='m60',],aes(x=B22dif,y=B22THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B22) + xlab('Time Elapsed (in hours)') + ggtitle('B22') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD')
```

```{r}
ggplot(data=df[df$type=='m46',],aes(x=B11dif,y=B11THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B11) + xlab('Time Elapsed (in hours)') + ggtitle('B11') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,100)
ggplot(data=df[df$type=='m46',],aes(x=B12dif,y=B12THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B12) + xlab('Time Elapsed (in hours)') + ggtitle('B12') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,100)
ggplot(data=df[df$type=='m46',],aes(x=B21dif,y=B21THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B21) + xlab('Time Elapsed (in hours)') + ggtitle('B21') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,100)
ggplot(data=df[df$type=='m46',],aes(x=B22dif,y=B22THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B22) + xlab('Time Elapsed (in hours)') + ggtitle('B22') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,100)
```

```{r}
ggplot(data=df[df$type=='m60',],aes(x=B11dif,y=B11THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B11) + xlab('Time Elapsed (in hours)') + ggtitle('B11') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
ggplot(data=df[df$type=='m60',],aes(x=B12dif,y=B12THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B12) + xlab('Time Elapsed (in hours)') + ggtitle('B12') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
ggplot(data=df[df$type=='m60',],aes(x=B21dif,y=B21THD)) + geom_hex(bins=40) + theme_bw() + facet_wrap(~B21) + xlab('Time Elapsed (in hours)') + ggtitle('B21') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
ggplot(data=df[df$type=='m60',],aes(x=B22dif,y=B22THD)) + geom_hex(bins=60) + theme_bw() + facet_wrap(~B22) + xlab('Time Elapsed (in hours)') + ggtitle('B22') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
```

```{r}
ggplot(data=df[df$type=='m60',],aes(x=B11dif,y=B11THD)) + geom_point(aes(x=B11dif,y=B11THD),color='dodgerblue',alpha=0.3) + theme_bw() + facet_wrap(~B11) + xlab('Time Elapsed (in hours)') + ggtitle('B11') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
ggplot(data=df[df$type=='m60',],aes(x=B12dif,y=B12THD)) + geom_point(aes(x=B21dif,y=B12THD),color='dodgerblue',alpha=0.3) + theme_bw() + facet_wrap(~B12) + xlab('Time Elapsed (in hours)') + ggtitle('B12') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,5)
ggplot(data=df[df$type=='m60',],aes(x=B21dif,y=B21THD)) + geom_point(aes(x=B21dif,y=B21THD),color='dodgerblue',alpha=0.3) + theme_bw() + facet_wrap(~B21) + xlab('Time Elapsed (in hours)') + ggtitle('B21') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,10)
ggplot(data=df[df$type=='m60',],aes(x=B22dif,y=B22THD)) + geom_point(aes(x=B22dif,y=B22THD),color='dodgerblue',alpha=0.3) + theme_bw() + facet_wrap(~B22) + xlab('Time Elapsed (in hours)') + ggtitle('B22') + theme(plot.title = element_text(hjust = 0.5)) + geom_line(aes(y=0),color="salmon",linetype = 2,size =1) + ylab('THD') + xlim(0,2)
```